{
  pkgs,
  config,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    clang-tools
    nixd
    gcc
    alejandra
    statix
    python3
    python3Packages.black
    python3Packages.matplotlib
    python3Packages.numpy
    python3Packages.manim
    stylua
    lua5_1
    lua51Packages.lua-lsp
    cmake
    gnumake
    cmake-language-server
    pyright
    marksman
    ltex-ls
    arduino-language-server
    bash-language-server
    shellcheck
    shellharden
    shfmt
    isort
  ];
}
